```{r read data}
library(dplyr)
train = read.csv("~/Downloads/titanic_train.csv")
test = read.csv("~/Downloads/titanic_test.csv")

```

```{r Gender Model}
summary(train$Sex)
table(train$Survived)/sum(table(train$Survived))
prop.table(table(train$Sex, train$Survived),1)

#Gender
test$Survived = 0 
test$Survived[test$Sex == "female"] = 1

#Age 
summary(train$Age)
train$Age[is.na(train$Age)] = mean(train$Age, na.rm = TRUE)

#Child
train$Child = 0 
train$Child[train$Age < 18] = 1
train$Child

#Aggregate 
aggregate(Survived ~ Child + Sex, data = train, FUN = function(x){sum(x)/length(x)} )


train$Fare2 <- '30+'
train$Fare2[train$Fare < 30 & train$Fare >= 20] <- '20-30'
train$Fare2[train$Fare < 20 & train$Fare >= 10] <- '10-20'
train$Fare2[train$Fare < 10] <- '<10'

featureClass = aggregate(Survived ~ Child + Sex + Fare2, data = train, FUN = function(x){sum(x)/length(x)} )

featureClass$Survived2 = ifelse(featureClass$Survived >= .5, 1,0)
temp = left_join(train, featureClass, by = c("Child" = "Child", "Sex" = "Sex", "Fare2" = "Fare2"))
head(temp)
```

```{r}

library(dplyr)

d1 <- data_frame(
  x = letters[1:3],
  y = LETTERS[1:3],
  a = rnorm(3)
  )

d2 <- data_frame(
  x2 = letters[3:1],
  y2 = LETTERS[3:1],
  b = rnorm(3)
  )
d1
d2
left_join(d1, d2, by = c("x" = "x2", "y" = "y2"))
```

```{r decision tree}
library(rpart)
fit <- rpart(Survived ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked,
               data=train,
               method="class")
plot(fit)
text(fit)


```

```{r}
install.packages('rattle')
install.packages('rpart.plot')
install.packages('RColorBrewer')
library(rattle)
library(rpart.plot)
library(RColorBrewer)



```